blank_issues_enabled: false
contact_links:
  - name: ğŸ“– README
    url: https://github.com/netr0m/az-pim-cli/blob/main/README.md
    about: Please take a look at the README.
  - name: â“ Questions
    url: https://github.com/netr0m/az-pim-cli/discussions
    about: If you have a question, or are looking for advice, please post on our Discussions forum!
